  //<![CDATA[
    $(".colorom a").each(function(){var o=$(this).attr("data-color");$(this).css("background-color",o),$(this).click(function(){return $(".menu ul li a,#copyrights a").css("color",o),$(".menu-tab li.active a,.posts-title h2,.post-readmore a,.contact-button a,#header-search .searchbox").css("background-color",o),$(".posts-title").css("border-color",o),$("#footer-wrapper").css("border-top-color",o),$(".post-sharebtn").hover(function(){$(this).css("background-color",o)},function(){$(this).css("background-color","#f4f4f4")}),$(".menu-bottom li a").hover(function(){$(this).css("background-color",o)},function(){$(this).css("background-color","#272727")}),$(".search-icon").hover(function(){$(this).css("background-color",o)},function(){$(this).css("background-color","rgba(255,255,255,0.1)")}),!1})}),$(".bground a").each(function(){$(this).click(function(){var o=$(this).find("img").attr("src");return $("body").css("background","url("+o+") repeat scroll top left"),!1})}),
$(document).on("click",".switchom.close",function(){return $(".switcher").css("margin-right","0"),$(this).removeClass("close"),$(this).addClass("opend"),!1}),
$(document).on("click",".switchom.opend",function(){return $(".switcher").css("margin-right","-240px"),$(this).removeClass("opend"),$(this).addClass("close"),!1}),
$(document).on("click",".contsho .full",function(){return $("#outer-wrapper").css("max-width","none"),$(".row").css("margin-left","auto"),$(".row").css("margin-right","auto"),$(".row").css("max-width","1152px"),!1}),
$(document).on("click",".contsho .full",function(){return $("#header-tail").css("max-width","none").css("margin-left","auto").css("margin-right","auto"),!1}),
$(document).on("click",".contsho .full",function(){return $("#header-tail-sticky-wrapper").css("margin-right","0px").css("margin-left","0px"),$("#ticker").css("max-width","none"),!1}),
$(document).on("click",".contsho .boxed",function(){return $("#outer-wrapper").css("max-width","1200px"),$(".row").css("margin-left","2%"),$(".row").css("margin-right","2%"),$("#header-tail").css("max-width","1200px"),$("#header-tail-sticky-wrapper").css("margin-right","0px"),!1});
    //]]>
